cyclejs/cyclejs

src/data-flow-source.js
test/data-flow-source.js

I think this is right. Feel free to change any/all of it. :beers:

copy keys from input to data flow source, fixes #54

---

docs/faq.md

No idea if the FAQ is the place for this, or even if it belongs, but I lost a few hours figuring this out and wanted to save others from the same fate. :grin:

Add note on events to FAQ

---

examples/many/many-model.js

Observables should contain `$` sign at the end.

Update name to be conventional

---

src/cycle.js

In https://github.com/staltz/rxmarbles/blob/master/src/components/marble.js#L2 you dig `svg` from internals of `Cycle`

Export svg hyperscript function

---

examples/many/many-intent.js

examples/many: ev.data is now called ev.detail (cf. 7a666ccf352877d753143e2c602749a48c47be18).

Fixed examples/many

---

src/web/custom-element-widget.js

Added getAll method to the property driver

---

package.json
src/cycle.js
test/cycle.js

There are definitely some rough edges, but it *does* pass the tests.

Update to RxJS 5.0.0-alpha.6

---

src/cycle.js
test/cycle.js

Add tests for `isolate()`.
Refactor to merge nested conditional statements and rename `responses` and `requests`.
Add initial documentation for `isolate()`

Auto scope

---

http/most-typings.d.ts
http/rx-typings.d.ts
http/rxjs-typings.d.ts
http/xstream-typings.d.ts

@staltz 
Tests need to be rewritten in TS too.
- [ x] I ran `npm test` for the package I'm modifying
- [x ] I used `npm run commit` instead of `git commit`
Remove response$$ from interfaces and fix filter and select signatures

fix(http): fix typings after removal of response$$

---

history/src/captureClicks.ts

ISSUES CLOSED: 430
Since the test for `captureClicks` was `.skip()`'d, I did not attempt to pass it for this fix.

fix(history): fix scope of captureClicks to properly exclude hash links

---

devtool/src/panel/view.ts

fix typo in the Gitter 'chat' URL that is shown when renderInvalidState is displayed and opens page in a new tab

fix(devtool): fix devtool Gitter chat-room link

---

http/package.json

feat(http): update to superagent v2.3.0

---

http/package.json
http/tsconfig.json

fix(http): remove @types/core-js in favor of tsconfig --options

---

http/README.md
http/src/http-driver.ts
http/src/interfaces.ts

Tried to add a test but got stuck, so tested manually.

feat(http): support SSL certificate authentication

---

base/src/index.ts
base/test/cycle.js

- [x ] I added new tests for the issue I fixed/built
- [ x] I ran `npm test` for the package I'm modifying
- [ x] I used `npm run commit` instead of `git commit`
ISSUES CLOSED: #476
This is a proposal of how #476 could be fixed.

fix(base): hold sinks emission until all sinks are subscribed

---

jsonp/jsonp.d.ts
jsonp/package.json
jsonp/src/index.ts
jsonp/tsconfig.json

Now using the new global adapt call, and TypeScript.

refactor(jsonp): rewrite jsonp driver for unified

---

README.md

Hi,
Tiny docs improvement :-)
Best regards,
Damian

Updated framework description in README

---

docs/.scripts/template.html
docs/api/dom.html
docs/api/history.html
docs/api/http.html
docs/api/index.html
docs/api/isolate.html
docs/api/jsonp.html
docs/api/most-run.html
docs/api/run.html
docs/api/rxjs-run.html
docs/basic-examples.html
docs/components.html
docs/dialogue.html
docs/drivers.html
docs/getting-started.html
docs/index.html
docs/model-view-intent.html
docs/releases.html
docs/streams.html
docs/theme/style.css

Doc fix, no tests for that.
- fixes "mixed content" warning (https page trying to load http://ghbtns.com).
- applies center to the text content, looks better

Small website fixes

---

docs/api/history.html
history/src/index.ts

Correct header for makeServerHistoryDriver documentation

---

.scripts/pre-check-release.sh
.scripts/release-whatever-needs-release.sh
.scripts/symlink-to-each-other.sh
.scripts/test-all.sh
.scripts/test-ci-all.sh
.scripts/yarn-x-for-all-packages.sh
Makefile

Add new scripts to run tests for all packages
ISSUES CLOSED: #584
Let's see if this works. In the longer term we should probably find a fully cross platform solution but hopefully this will support OSX and Linux.

chore(META): fix makefile on linux to fix build

---

history/src/index.ts

since I'm modifying the docs, no test were ran.
Also, `yarn run commit` does not seem to work but I followed as closely as I can on the commit standards.
This is part of a series of small PRs for #583

docs(history): adds small example on makeHistoryDriver

---

history/src/index.ts

docs(history): adds example for captureClicks

---

http/.testem.json
http/src/http-driver.ts
http/src/index.ts
http/src/interfaces.ts
http/test/browser/src/index.ts
http/test/support/server.ts

Add feature to handle binary response to cycle/http.

Enable to handle binary response

---

dom/package.json

The same issue as here: https://github.com/snabbdom/snabbdom/pull/296

Fix wrong VNodeData typings

---

dom/src/index.ts

docs(dom): remove stream adapter section from mockDOMSource

---

Makefile
dom/yarn.lock

chore(META): add make lib all target

---

CONTRIBUTING.md

chore(META): add step for yarn installation to CONTRIBUTING.md

---

.scripts/minify.js
Makefile
dom/package.json
history/package.json
html/package.json
http/package.json
isolate/package.json
jsonp/package.json
most-run/package.json
package.json
run/package.json
rxjs-run/package.json
yarn.lock

perf(META): use Google Closure Compiler instead of uglify-js

---

devtool/README.md
devtool/src/panel/view.ts

docs(devtool): use correct package name in devtool docs

---

docs/index.html

tricycle is now part of the cyclejs organization.
ISSUES CLOSED: #534

docs(META): update link to tricycle

---

dom/src/hyperscript-helpers.ts

fix(dom): add support for "time" hyperscript-helper

---

docs/README.md

docs(META): add a docs README with a warning about editing html output

---

docs/theme/style.css

Fix header position in home page.

---

dom/package.json
dom/src/VNodeWrapper.ts
dom/src/makeDOMDriver.ts
dom/src/utils.ts
dom/test/browser/src/render.tsx
dom/yarn.lock

Which supports mounting on a DocumentFragment, and (breaking change:) boolean attrs.
BREAKING CHANGE:
Snabbdom 0.7.0 has some breaking changes, see their release notes:
https://github.com/snabbdom/snabbdom/releases/tag/v0.7.0
ISSUES CLOSED: #656

fix(dom): update snabbdom to v0.7.0

---

Makefile
dom/package.json
dom/tsconfig.json
history/package.json
history/tsconfig.json
html/package.json
html/tsconfig.json
http/package.json
http/tsconfig.json
isolate/package.json
isolate/tsconfig.json
jsonp/package.json
jsonp/tsconfig.json
most-run/package.json
most-run/tsconfig.json
run/package.json
run/tsconfig.json
rxjs-run/package.json
rxjs-run/tsconfig.json
time/package.json
time/tsconfig.json
tsconfig.common.json

Add ES6 module builds

---

dom/src/IsolateModule.ts
dom/test/browser/src/isolation.ts

Initially, vnodes were cleaned (EventListener destroyed) during the snabbdom's \`remove\` or \`destroy\`
hook. Thus, if the vnode is, in fact, used latter on in the DOM, those listeners are now gone.
This patch only removes those nodes at the end of snabbdom's process. Thus if the nodes are needed
latter on, they won't be destroyed
ISSUES CLOSED: #667

fix(dom): wait for snabbdom's post hooks to clean vnodes (#667)

---

dom/src/DOMSource.ts
dom/src/EventDelegator.ts
dom/src/fromEvent.ts
dom/test/browser/src/events.ts

This is just a rebase + continuation of PR #615, deployed to a different branch because #615 was in Jan's own repo.

Conditional predicate, a continuation of PR #615

---

http/src/http-driver.ts
http/src/index.ts
http/src/interfaces.ts
http/test/node.ts

ISSUES CLOSED: #681
Hello, 
I only add one test for this feature, tell me if it's enough.
I hope this help.
Nicolas

feat(http): implement `ok` field in request objects

---

http/src/MainHTTPSource.ts
http/src/interfaces.ts
http/src/isolate.ts
http/test/browser/src/common.ts

fix(http): check position of isolation namespace

---

isolate/src/index.ts

docs(isolate): document isolate as non type transparent

---

history/package.json

fix(history): update history to v4.7.x

---

examples/basic/hello-world/README.md

This is related to #480 
Here is a proto-README for the hello world example. I intend to use whatever comes out of the PR as guidelines for other READMEs. So please help me make an awesome README for beginners like me.
My goal here was twofold:
1. Have this file stand for itself. This is useful for people going directly into the individual examples.
2. Make the file fit in some kind of curriculum for learning. I'm focusing here on folks that have already had some other intro to cyclejs and are looking for example code to level up.

docs(examples): add a README for the hello-world example

---

http/package.json
http/src/isolate.ts
http/test/browser/src/common.ts
http/yarn.lock

fix(http): fix isolation regression

---

html/src/makeHTMLDriver.ts
html/test/index.ts

fix(html): error handling for makeHtmlDriver method

---

dom/src/MainDOMSource.ts

fix(dom): fix .elements() support for rxjs and most

---

isolate/src/index.ts

feat(isolate): add \`toIsolated\` returning a higher order component

---

dom/src/hyperscript-helpers.ts

Add support for importing <details> and <summary> from @cycle/dom

---

dom/package.json
dom/yarn.lock

fix(dom): update snabbdom-selector

---

time/.markdown-doctest-setup.js
time/README.md
time/package.json
time/rxjs.ts
time/src/mock-time-source.ts
time/test/rxjs.ts
time/test/time.ts

Targeting the same version as rxjs-run.

chore(time): upgrade rxjs dependency to 6.2.x

---

examples/intermediate/animation/src/main.js

docs(examples): fix import path in animation example

---

browserstack-karma.js

test(dom): test against old Firefox and UC Browser (Android)

---

docs/content/documentation/drivers.md

docs(META): fix typo in drivers document

---

.cz-config.js
.scripts/check-release.js

chore(META): remove some commit types, use chore type more

---

dom/package.json
dom/shrinkwrap.yaml
dom/test/browser/isolation.ts

fix(dom): update snabbdom

---

dom/test/node/mock-dom-source.ts

chore(dom): remove zombie transposition use in tests

---

time/src/debounce.ts
time/src/delay.ts
time/src/throttle-animation.ts
time/src/throttle.ts
time/test/time.ts

fix(time): unsubscribes Time operators on complete

---

dom/src/most.ts
dom/src/rxjs.ts

fix(dom): fix rxjs and most typings of makeDOMDriver

---

dom/src/hyperscript-helpers.ts
dom/test/browser/isolation.ts
tslint.json

fix(dom): add better typings for the hyperscript helpers

---

docs/content/api/state.md

Fix missing type argument @ Reducer

---

history/src/createHistory$.ts
history/src/types.ts
history/test/browser/rxjs.ts
history/test/browser/xstream.ts

feat(history): complete support for history.push API

---

dom/package.json
isolate/package.json
most-run/package.json
package-lock.json
package.json
rxjs-run/package.json
shrinkwrap.yaml

Update typescript to 3.2.4

---

dom/src/makeDOMDriver.ts
html/src/makeHTMLDriver.ts

Addresses  #922.
Should I add some test cases for this change?
Since this PR introduces very trivial changes, I wonder which kind of test cases I should add 🤔

Make reportSnabbdomError configurable

---

dom/src/index.ts
html/src/index.ts

This PR is a successor of https://github.com/cyclejs/cyclejs/pull/923
I've updated docs to note about `reportSnabbdomError`.

Add docs about reportSnabbdomError

---

.travis.yml
dom/package.json
http/package.json
http/test/browser/common.ts
http/test/browser/index.ts
http/test/browser/setup.ts
pnpm-lock.yaml

Let's hope this is green again now

fix errors in CI

---

dom/src/makeDOMDriver.ts

feat(dom): accept partial modules in DOMDriverOptions

---

http/src/isolate.ts

fix(http): do not mutate the request in isolate

---

history/package.json
history/src/createHistory$.ts
history/src/drivers.ts
pnpm-lock.yaml

[history] Update `history` to v5

---

CONTRIBUTING.md
docs/content/index.md

* update link to egghead course
* update egghead timing
* update pnpm installation link

docs(META): update dead links
