src/renderer.js, test/phantomjs/renderer.js
Currently it's impossible to use Cycle.js with custom elements and Shadow DOM, because shadowRoot is DocumentFragment, not HTMLElement. As far as I see, virtual-dom package works fine with DocumentFragment too, so I see no reason to prevent usage of it in Cycle.
=> Add support for DocumentFragment as input for renderer

src/custom-element-widget.js, src/render-dom.js, test/browser/custom-elements.js, test/browser/render.js
Diff at test/browser/custom-elements.js:L226 shows exception could be silently thrown even if the element was actually rendered. I think this is a drawback developers would encounter often.
And this shows we might need a additional parameter for skip the rendering in applyToDOM and another `subscribe` method for doing `rootElem$.connect()` and `rootElem$.subscribe()`.
```
// TODO: cannot dispose because applyToDOM has not yet completed.
```
The above todo comment in the test shows that subscribe method is necessary for properly disposing domUI after this change was made.
=> nostream: Always subscribe rootElem$ for better error handling

src/custom-element-widget.js, src/custom-elements.js, test/browser/custom-elements.js
This is a retry of #111. All test passed. `synthetic-examples/nested-custom` has been tested and no problem found. The test for that example has not yet been written in this PR, however.
=> nostream: Properly dispose resources after the custom-element has been destroyed

cycle.d.ts
Currently this has the definitions for both core and web (mainly because there isn't a typescript branch on web :) ).  I'm not sure if we want to split them up or not; given that there are only likely to be a few drivers for the moment it might be easier to keep them together.  Let me know what you think!
=> Initial commit of Typescript definitions.

package.json
```Rx.Observable.fromEvent``` is broken in rx@4.0.1 and fixed in 4.0.6. This affects drivers that are importing ```Rx``` via ```@cycle/core```.
=> Updated to rx 4.0.6 to fix fromEvent

package.json
due to bug in npm:
- https://github.com/npm/npm/issues/6581#issuecomment-174718361
- https://github.com/facebook/react/issues/5918#issuecomment-174710988
This bug breaks bundling modules via [browserify-cdn](https://wzrd.in/). Please merge this and patch version ASAP. Thanks!
=> add empty dependencies object

src/cycle.js
1. Replace `for in` with `Object.{keys, values}`. Why?
* It is harmony-way to handle objects
* Less code: removes repetition of `hasOwnProperty` calls
* More functional: `reduce` operates only on parameters
* Semantically correct: `for in` is for enumerating prototype chain, `Object.keys` is for own props
* Cross-browser: in ES5 `for in` was slightly changed and only Firefox implemented new behaviour (see [compat-table](https://github.com/kangax/compat-table/blob/gh-pages/data-es5.js#L1325) for details)
* Faster: `let` creates unnecessary binding on every iteration. `for in` may prevent the whole function from being optimized by V8 (see [optimization-killers](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#52-the-object-being-iterated-is-not-a-simple-enumerable) for …
=> Tiny refactoring and optimization

README.md
Really minor detail but: `@cycle/foo` can be misleading given there is no real `@cycle/foo` package or `foo` directory. For really quickly understanding the sentence I would use a specific package included in the project, like `base`.
=> Make packages explanation specific to the project

http/package.json
The jspm's main file is incorrect, it shouldn't be using the compiled version, this also fix #237.
We don't need this as jspm will automatically look for main by default.
=> Remove jspm from package.json

examples/tsx-seconds-elapsed/.babelrc, examples/tsx-seconds-elapsed/.gitignore, examples/tsx-seconds-elapsed/index.html, examples/tsx-seconds-elapsed/package.json, examples/tsx-seconds-elapsed/src/index.tsx, examples/tsx-seconds-elapsed/tsconfig.json, examples/tsx-seconds-elapsed/typings.json, typings.json
Tried my luck with it and got it working with Babel and the TypeScript compiler.
I preserve the JSX and let Babel handle the conversion, because `tsc` always emits `createElement`
This has the drawback, that `tsc` completely ignores the JSX and removes the `snabbdom-jsx` imports.
I prevented the removal with `const {html} = require('snabbdom-jsx')` inside the `.tsx` file.
The alternative would be a wrapper for `snabbdom-jsx` that has a `createElement` method (https://github.com/yelouafi/snabbdom-jsx/issues/8#issuecomment-230998185)
=> Add example for TSX #350

README.md
Simple readme link for packages.
=> docs(META): add packages link to readme

examples/bmi-nested/src/BmiCalculator.js, examples/bmi-nested/src/LabeledSlider.js
I refactored the bmi-nested example to use the [Model-View-Intent pattern](http://cycle.js.org/model-view-intent.html) during lunch to play around with cyclejs. I also moved `isolate` back to the component (which now [exports a fn which calls isolate](http://cycle.js.org/components.html#Should-I-always-call-isolate-manually)) and changed the sinks keys' name to [not use the stream convention](http://cycle.js.org/components.html#how-to-name-sources-and-sinks).
These changes were for my own learning, but figured I'd make a PR in case you would rather have the example follow this pattern.
=> refactor(examples): refactor bmi-nested to use MVI pattern

most-run/src/index.ts, most-run/test/index.js, rx-run/test/cycle.js, rxjs-run/test/cycle.js, xstream-run/test/cycle.js
Allows `import {run} from 'most-run'` usage. Also includes corresponding test for all *-run packages to prevent things like #411.
=> fix(most-run): export run funcrion

http/src/http-driver.ts
There is no reason to represent response$$ using a MemoryStream, it is not a value-over-time, HTTP responses are events
=> fix(http): remove 'remember()' from response$$, not value-over-time

dom/src/isolateModule.ts, dom/test/browser/isolation.js
Here's a proposed fix to #409.
The added test case fails on master and passes w/ this new change. I'm reusing `isolatedElements` as a way to check whether the element has been replaced by a new instance (when the parent is recreated, the create hook seems to run first and then the old node gets destroyed).
=> Fix isolated component events after parent is recreated

rxjs-adapter/src/index.ts
=> fix(rxjs-adapter): fixes isValidStream, broken by xstream v6.3

dom/package.json, dom/src/MainDOMSource.ts, dom/src/makeDOMDriver.ts, dom/test/browser/dom-driver.js, dom/test/manual-tests/advanced-list/src/app.js, dom/test/manual-tests/advanced-list/src/main.js
When `dispose()` was called, the virtual DOM tree wasn’t cleaned properly;
thus, `destroy` hooks on elements (widgets) wouldn’t work and could cause
leaks and side effects.
With this fix, calling `dispose()` destroys the virtual DOM tree that was
created and cleans up all produced effects.
Closes #263
=> fix(dom): add virtual DOM sanitation on `dispose()`

devtool/package.json, devtool/tsconfig.json, dom/package.json, dom/tsconfig.json, xstream-adapter/package.json, xstream-adapter/tsconfig.json
for dom, xstream-adapter, devtool
ISSUES CLOSED: #454
=> fix(META): substitute core-js and es6-shim with --lib options 

dom/package.json, dom/src/MainDOMSource.ts, dom/test/browser/events.js
This is a fix for a bug I encountered which is replicated here: http://github.com/ntilwalli/isolateTest
When the DomTest component is isolated I was not able to restart the `itemMouseUp$`
The fix pulls the `hadIsolated_mutable` value out of the closure and into the stream state to ensure that restarted subscriptions cause the `hadIsolated_mutable` value to be reinitialized to `false` (when it wasn't being reinitialized, the remembered DOM was being filtered out for all restarts of the isolated events stream)
__Notes:__ the `isolateTest` uses a local copy of `rxjs-adapter` due to a bug introduced into `rxjs-adapter` a few days ago when `xstream` was updated.  The fix submitted in https://github.com/cyclejs/cyclejs/pull/438 is required and must be installed for that repo to properly …
=> fix(dom): enable restarting of event streams on isolated components

http/README.md
The declared stream and the returned one weren't matching.
=> Renamed vdom$ to vtree$

dom/src/hyperscript.ts
The addNS errors on svg "text" elements since their children are simple strings which don't have
VNode properties.  This PR skips addNS processing for "text" children.
ISSUES CLOSED: #473
=> fix(dom): skip calling addNS on svg "text" children

most-adapter/package.json, most-adapter/src/index.ts, most-adapter/tsconfig.json, most-run/package.json
This PR simply updates the dependencies of `most-adapter` to the latest of most, most-subject, and @most/create with minor build changes to fix compilation errors with their improved typings.
Updates the `most-run` dependencies as well to match that of `most-adapter`.
=> Update most-run and most-adapter to latest versions of their dependencies

dom/src/index.ts
The existence of `ownerTarget` is not very obvious to `cycle/dom` users. Hence the README is updated to reflect the existence of it.
=> docs(dom): update README to include ownerTarget

dom/README.md, dom/src/index.ts
Clarified that DOMDriverOptions overrides @cycle/dom's default Snabbdom modules, and linked to the TypeScript definition file where those defaults are defined.
Changed wording to "property" instead of "field" in a couple spots.
Issue #471
PR #472
ISSUES CLOSED: #471
=> docs(dom): clarify makeDOMDriver's Snabbdom module override behavior

dom/src/EventDelegator.ts, dom/test/browser/events.js
Searching the body will not find the element inside a DocumentFragment or shadowRoot, so the function ends up exiting early and the event is ignored. Added a test for a click inside a DocumentFragment, behaviour is similar to shadowRoot but has better browser support.
ISSUES CLOSED: #412
=> fix(dom): change EventDelegator bubble to search topElement instead of body

rxjs-adapter/src/index.ts
Hi there  
I noticed that my bundle is really large and find out that rxjs-adapter load the entire rxjs5 library.  
It would be nice to only bundle what necessary to the adapter.
=> refactor(rxjs-adapter): scope down rxjs module importing

base/.npmignore, dom/.npmignore, history/.npmignore, jsonp/.npmignore, most-adapter/.npmignore, most-run/.npmignore, rx-adapter/.npmignore, rx-run/.npmignore, rxjs-adapter/.npmignore, rxjs-run/.npmignore, xstream-adapter/.npmignore, xstream-run/.npmignore
It's not needed anyway. It's also causing issues when used with React-Native packager, which processes node_modules with Babel
(https://github.com/reactjs/redux/issues/1033#issuecomment-156584084)
=> chore(META): exclude .babelrc from NPM builds

http/src/http-driver.ts, http/test/common.js
The request object is added to the superagent response object on non error statuscodes. On error the request object is unavailable in the error's response object. This pull request fixes that.
=> feat(http): added request object to http err response

dom/src/mockDOMSource.ts
Just happened to be looking at the `mockDOMSource` code and it seemed like it could be improved.
I feel like there's something I've missed and it was done this way originally for a reason.
The tests pass with this change. I haven't benchmarked it, but it should be more performant (`O(1)` instead of `O(n)`).
=> refactor(dom): simplify implementation of mockDOMSource.select() and .events()

history/src/createHistory$.ts, history/test/browser/common.ts, history/test/browser/rxjs.ts, history/test/browser/xstream.ts, history/test/node/common.ts, history/test/node/rxjs.ts, history/test/node/xstream.ts
This fixes a bug introduced in d41bdae74904746e0a8983a77305f5bbf3a326c4
=> fix(history): fix history drivers to start emitting the current location

docs/basic-examples.html, docs/content/documentation/basic-examples.md, examples/http-random-user/src/index.ts
The [get random user example](https://cycle.js.org/basic-examples.html#basic-examples-http-requests) doesn't seem to be working because https://cycle.js.org/ is served over HTTPS but hitting the HTTP version of jsonplaceholder.typicode.com.
This PR replaces `http://jsonplaceholder.typicode.com` to `https://jsonplaceholder.typicode.com`. Tested in `examples/basic-examples.html` and the HTTPS version works.
=> Use HTTPS for jsonplaceholder endpoints

rxjs-run/src/index.ts
[import only what you need by patching](https://github.com/ReactiveX/rxjs#es6-via-npm)
BREAKING CHANGE:
Consumer will need to add operators individually. (Inspired by [redux-observable](https://github.com/redux-observable/redux-observable/blob/master/docs/Troubleshooting.md#rxjs-operators-are-missing-eg-typeerror-actionoftypeswitchmap-is-not-a-function))
ISSUES CLOSED: #510
=> fix(rxjs-run): optimize bundle size of rxjs

docs/.scripts/template.html, docs/api/index.html, docs/basic-examples.html, docs/components.html, docs/dialogue.html, docs/docsearch.js, docs/drivers.html, docs/getting-started.html, docs/index.html, docs/model-view-intent.html, docs/releases.html, docs/streams.html, docs/theme/style.css
Hi @staltz, following your request on the https://community.algolia.com/docsearch/ website, we went further and actually implemented the search input inside Cycle.js docs. I hope you don't mind.
All details have been sent via email too.
**Live demo**: https://docs-uvevkwxznz.now.sh.
Every time you'll select an item for search it redirects to main website, that's expected so you will have to go back to try again.
<details>
<summary>Demo GIF</summary>
</details>
=> docs(search): Add Algolia's DocSearch to allow searching in docs

history/src/drivers.ts, history/src/index.ts, history/test/browser/common.ts, history/test/node/common.ts
Allow clients to inject history object directly, useful to libs like cyclic-router which need access
to raw history object's createHref functionality
ISSUES CLOSED: #551
=> feat(history): polymorphic makeHistoryDriver, allow History object for options

docs/content/documentation/getting-started.md
As the one-fits-all flavor is the only typescript flavor that is compatible with caa v3
=> docs(META): add typescript scaffold instructions

README.md
Markdown headings "Support" and "Backers" were missing a space. Also "Sponsors" seemed like it should be an H3 based on context.
- [n/a] I added new tests for the issue I fixed/built
- [n/a] I ran `yarn test` for the package I'm modifying
- [n/a] I used `yarn run commit` instead of `git commit`
=> README: fix markdown headings near "Support"

examples/animated-letters/package.json, examples/animated-letters/src/main.js, examples/autocomplete-search/package.json, examples/autocomplete-search/src/app.js, examples/autocomplete-search/src/main.js, examples/custom-driver/package.json, examples/custom-driver/src/main.js, examples/http-search-github/package.json, examples/http-search-github/src/main.js, examples/jsx-seconds-elapsed/package.json, examples/jsx-seconds-elapsed/src/main.js, examples/tsx-seconds-elapsed/package.json, examples/tsx-seconds-elapsed/src/index.tsx
Closes #575.
I have left the examples that use tween intact, as this is blocked on https://github.com/cyclejs/time/issues/13, which still requires a bit of discussion.
I have made the commits separately for each example I updated so that interested parties could see each one individually, but it might make sense to squash it all together upon merge.
I have manually tested that all examples work the same. 😸
=> Use @cycle/time in examples

docs/api/dom.html, dom/src/index.ts
mockDOMSource missing closing bracket. Has a visible effect - the following sentence is shown in <code>.
=> Documentation: Fix typo. Add missing backtick

history/src/index.ts
This PR is part of a series of small PRs for #583 
Moving `captureClicks` below might seem trivial but it makes more sense for people to understand the history driver first before knowing that you can use `captureClicks` to wrap around it. Especially after we add code examples.
=> docs(history): re-order capture click to be after makeHashHistoryDriver

dom/src/BodyDOMSource.ts, dom/src/DOMSource.ts, dom/src/DocumentDOMSource.ts, dom/src/MainDOMSource.ts, dom/src/index.ts, dom/test/browser/src/events.ts
This would remove impure `preventDefault` calls inside the app. Usage:
```javascript
const event$ = sources.DOM.select('.myform').events('submit', { preventDefault: true });
//currently
const event$ = sources.DOM.select('.myform').events('submit')
.map(ev => {
ev.preventDefault();
return ev;
});
```
=> feat(dom): add preventDefault option

dom/src/BodyDOMSource.ts, dom/src/DocumentDOMSource.ts, dom/src/EventDelegator.ts, dom/src/MainDOMSource.ts, dom/src/fromEvent.ts, dom/test/browser/src/events.ts
These are most of the changes I was originally going to submit for #65 before #603 beat me to the punch. The main difference is that this does not manipulate the event streams themselves. This also incorporates support for the `preventDefault` option being a function, which was supposedly part of #603 as well before being scrapped for some reason. Not sure these are even still necessary, but who am I to judge?
I suspect some things I did might be slightly bold, so I'd love to hear your opinion.
=> refactor(dom): preventDefault does not manipulate stream

isolate/src/index.ts
when grepping the site for a `null` example, I overread the sentence three times.
An example is helpful here
=> refactor(docs): add example with null scope

time/package.json, time/src/periodic.ts, time/src/time-driver.ts
Previously, all events were driven by requestAnimationFrame. When a tab loses focus, requestAnimationFrame stops executing. By using setImmediate instead, events will fire in the background.
.animationFrames() and .throttleAnimation are still powered by requestAnimationFrame, so will not fire when the tab has lost focus.
Fixes https://github.com/cyclejs/time/issues/37. Progresses #635.
=> feat(time): use setInterval to run events in background

docs/api/dom.html, dom/src/index.ts, dom/test/browser/src/isolation.ts, dom/test/browser/src/select.ts
I don't know why the CHANGELOG has been affected by this commit, I just edited the appropriate files and ran `make test dom` & `make commit`
related to https://gitter.im/cyclejs/cyclejs?at=5979ccdac101bc4e3ac5b82b
=> Put svg attributes inside attrs object

dom/src/IsolateModule.ts, dom/src/makeDOMDriver.ts
This is a follow-up to the recent ES6 module build, as per the comment here: https://github.com/cyclejs/cyclejs/pull/662#issuecomment-325375349
The map polyfill was being `require()`d, which was breaking the build when used as ES6 modules. Switched these requires to `import` statements following @jvanbruegge's reply.
=> Switch map polyfill to import statement to make ES6 module build work

time/README.md, time/most.ts, time/rxjs.ts, time/src/debounce.ts, time/src/delay.ts, time/src/diagram.ts, time/src/mock-time-source.ts, time/src/periodic.ts, time/src/scheduler.ts, time/src/throttle-animation.ts, time/src/throttle.ts, time/src/time-driver.ts, time/src/time-source.ts, time/src/types.ts, time/test/time.ts
Also, rename scheduler.completion to scheduler.complete for consistency
with xstream addListener names.
Closes https://github.com/cyclejs/time/issues/31
=> feat(time): support creating custom operators with Time.createOperator()

http/src/index.ts, http/src/interfaces.ts, http/test/browser/src/common.ts
> By default sending strings will set the `Content-Type` to `application/x-www-form-urlencoded`.
Example from the document of superagent:
```js
request.post('/user')
// object
.send({ name: 'tj' })
// or string
.send('name=tj')
...
```
Ref: http://visionmedia.github.io/superagent/
=> fix(http): allow string type for send property

docs/content/documentation/drivers.md
I just fixed a typo and removed one `)`.
=> fixed typo in example

dom/src/DOMSource.ts
The lib.dom.d.ts file contains a mapping where the name of the event type is mapped to the event
type itself (e.g. click -> MouseEvent). Using this mapping on the DOMSource.events() function allows
the correct event stream to be returned.
=> feat(dom): overload .event() method using HTMLElementEventMap

examples/nested-folders/package.json, examples/nested-folders/src/Folder.js
Updated the nested folders example to use the new Collection API from the Onionify 4.0 Library.
=> refactor(examples): updated nested folders example

dom/src/MainDOMSource.ts
This fixes an issue I had where a parent component would receive a `change` event from an isolated child component. It seems a trivial bug: `change` is treated as non-bubbling while in fact [it does bubble](https://developer.mozilla.org/en-US/docs/Web/Events/change#General_info).
=> Remove "change" from eventTypesThatDontBubble

dom/es6-map.d.ts, dom/src/IsolateModule.ts, dom/src/makeDOMDriver.ts, dom/tsconfig.json
As stated in the README of es6-map, the algorithmic complexity of the poly-/ponyfill is O(n) not
O(1). As almost all browsers have native ES6 Map support nowadays, we should use them and only
polyfill if needed
=> refactor(dom): use native ES6 Map

time/package.json
I'm using cycle/time in a demo React Native app, and noticed that it won't run because `chalk` (used by `variable-diff`) expects a node.js environment. This PR ignores node.js-specific modules like that one.
=> fix(time): ignore node.js specific modules in React Native

dom/src/BodyDOMSource.ts, dom/src/DOMSource.ts, dom/src/DocumentDOMSource.ts, dom/src/ElementFinder.ts, dom/src/MainDOMSource.ts, dom/test/browser/src/dom-driver.ts, dom/test/browser/src/elements.ts, dom/test/browser/src/events.ts, dom/test/browser/src/index.ts, dom/test/browser/src/isolation.ts, dom/test/browser/src/render.tsx, dom/test/browser/src/select.ts
MainDOMSource.elements() now always returns an array of Elements, return types of the other
DOMSources are correctly inferred
ISSUES CLOSED: #677
=> refactor(dom): make DOMSource.elements() monomorphic

dom/src/BodyDOMSource.ts, dom/src/DOMSource.ts, dom/src/DocumentDOMSource.ts, dom/src/ElementFinder.ts, dom/src/MainDOMSource.ts, dom/src/index.ts, dom/src/mockDOMSource.ts, dom/test/browser/src/dom-driver.ts, dom/test/browser/src/elements.ts, dom/test/browser/src/events.ts, dom/test/browser/src/index.ts, dom/test/browser/src/isolation.ts, dom/test/browser/src/render.tsx, dom/test/browser/src/select.ts
MainDOMSource.elements() now always returns an array of Elements, return types of the other
DOMSources are correctly inferred
ISSUES CLOSED: #677
BREAKING CHANGE: `elements()` now always returns an array of elements if
you pass a selector
=> fix(dom): make DOMSource.elements() monomorphic

html/package.json, html/src/HTMLSource.ts, html/src/index.ts, html/yarn.lock
Update snabbdom. Update snabbdom-to-html. Update cycle/dom, and with it, introduce also
HTMLSource.element() in order to properly implement the DOMSource interface.
ISSUES CLOSED: #725
=> fix(html): update important dependencies

docs/content/api/dom.md, docs/content/api/history.md, docs/content/api/html.md, docs/content/api/http.md, docs/content/api/isolate.md, docs/content/api/most-run.md, docs/content/api/run.md, docs/content/api/rxjs-run.md
If this is useful, another option would be to include the source links in the index instead.
=> docs(META): add links to source for each package in api reference

docs/content/api/dom.md, dom/package.json, dom/src/makeDOMDriver.ts, dom/src/utils.ts, dom/test/browser/page/index.html, dom/test/browser/src/dom-driver.ts, dom/test/browser/src/elements.ts, dom/test/browser/src/events.ts, dom/test/browser/src/isolation.ts, dom/test/browser/src/render.tsx, dom/test/browser/src/select.ts, dom/yarn.lock, http/package.json, http/test/browser/src/index.ts, http/yarn.lock, run/package.json, run/src/index.ts, run/src/microtask.ts, run/src/types.ts, run/test/index.ts, run/yarn.lock, rxjs-run/package.json, rxjs-run/test/index.ts, rxjs-run/yarn.lock
=> Fix driver race condition on sinks, fix DOM driver mutations in loop

history/src/captureClicks.ts, history/test/browser/common.ts
Ensure the document event listener added when using captureClicks
is properly removed when the sink passed to the driver is disposed of
ISSUES CLOSED: #734
=> fix(history): fix captureClicks listener cleanup

run/src/index.ts, run/test/index.ts
Error/exception reporting no longer expects there to be a stack trace on the error object. Any
error, even if it was `throw 'error-as-string'` will be reported as is.
ISSUES CLOSED: #687
=> fix(run): make exception reporting less opinionated

time/most.ts, time/rxjs.ts, time/src/debounce.ts, time/src/periodic.ts, time/src/throttle-animation.ts, time/src/throttle.ts, time/src/time-driver.ts, time/src/time-source.ts, time/test/time-driver.ts
Fixes #754.
This is a very bad bug, that I really should have caught. I never handled error events in the production scheduler, so any scheduled error was swallowed.
To address this, I have added a unit test, handled the error case, added a safeguard runtime error to ease regression detection, and then short-circuited the scheduler for the majority of the cases where this would occur.
I also added a simple dispose function for the unit test, that will still need to be elaborated in future.
=> Fix error propagation in @cycle/time

time/src/time-driver.ts
Make sure time driver doesn't throw an 'Unhandled event type' error for valid event types
There are no unit tests for this change currently - as mentioned in https://github.com/cyclejs/cyclejs/commit/82f313e693b8e1374d175a892c81d3f7c2729a14 having a few unit tests of basic functionality in https://github.com/cyclejs/cyclejs/blob/master/time/test/time-driver.ts would be really useful. I may be able to find some time to write a few tests this weekend... :)
https://github.com/cyclejs/cyclejs/issues/772
=> fix(time): fix event processing

time/most.ts, time/package.json, time/rxjs.ts, time/tsconfig.json
Fixes #779.
I recognise that this doesn't allow most/rxjs users to use ES6 sources, I but I think that having it work at all would be an improvement over the current situation. We should tackle ES6 sources in a separate PR.
=> fix(time): fix rxjs and most entrypoints

.scripts/bump.js, Makefile, package.json, yarn.lock
Closes #737.
Unlike bump-cli, bump.js can bump from 19.0.0 to 20.0.0, rather than to
110.0.0.
=> chore(META): replace bump-cli with simple bump script

dom/src/makeDOMDriver.ts
The elementAfterPath$ stream was immediately sampled, while elementAfterPath$ only starts emitting
once the DOM is ready, causing the first emission of elementAfterPath$ to be missed. By postponing
the first sample of elementAfterPath$ until the DOM is ready, we make sure that we don't miss this
first emission.
ISSUES CLOSED: #791
=> fix(dom): postpone sampling of root element until DOM is ready.

dom/yarn.lock, time/package.json
This pr changed `tsc` command to pointed to the local installed the version. One doesn't install `tsc` globally will encounter an error `tsc: command not found`.
ran test `make test time` and committed using `make commit`.
=> chore(META): add path to local installed tsc

package.json, rxjs-run/package.json, rxjs-run/src/index.ts, rxjs-run/test/index.ts, rxjs-run/yarn.lock, yarn.lock
This PR update rxjs-run to be able to use rxjs6.
=> Update rxjs-run to use rxjs6

run/src/index.ts, run/src/internals.ts, run/src/types.ts, run/test/setupReusable.ts
We should be able to dispose the reusable resources or dispose one specific run.
ISSUES CLOSED: #824
=> fix(run): add two kinds of dispose() for setupReusable()

isolate/package.json, isolate/src/index.ts, isolate/test/index.ts, isolate/yarn.lock
Rxjs 6 uses a piping semantic which removes the existence of the map prototype from the base
Observable class, this change ensures that each sink stream is adapted to xstream before
isolation
operations are applied.
BREAKING CHANGE:
This update changes the contract such that xstream and @cycle/run are now dependencies.
ISSUES CLOSED: #826
=> fix(isolate): adapt sinks so xstream semantics can be applied

dom/package.json, html/package.json, http/package.json, isolate/CHANGELOG.md, isolate/package.json, isolate/src/index.ts, isolate/test/index.ts, shrinkwrap.yaml, state/CHANGELOG.md, state/package.json, state/test/withState.ts
**Do not merge yet**
This PR just shows *what kind of breaking changes* would happen if we would introduce TypeScript's `unknown` instead of `any`. The purpose is to avoid sneaking `any` types that tend to virally propagate, and instead to use `unknown` which forces the developer to cast the type of some sinks returned from an isolated component. In other words, `isolate` would never give `any` types, it would force the developer to think about what type they expect.
Open for discussion before I do the following:
=> WIP use TypeScript `unknown` in isolate

CONTRIBUTING.md
ISSUES CLOSED: #908 
This is a very simple documentation update
=> docs(META): clarify that you need to build before running tests

karma.conf.js
Due to #901 the builds are not grouped any more in the browserstack ui. This should fix that
=> chore(META): group browserstack sessions by build number

rxjs-run/package.json
This fixes a bug described in https://github.com/cyclejs/cyclejs/issues/902
This issue likely affects other libs where `peerDependencies` were erroneously removed in favor of `dependencies`.  This is definitely a bug in the context of `rxjs-run`.
- [x ] There exists an issue discussing the need for this PR
- [x ] I used `pnpm run commit` instead of `git commit`
=> Convert rxjs-run deps to peerDeps

dom/src/EventDelegator.ts, dom/test/browser/events.ts
Setup and add nonBubbling listeners before the stream starts.
I was reading the code for #940, there is an if statement that looks like it wants to differentiate between the first nonBubbleing listener and the rest, by looking for existing listeners in `this.nonBubblingListeners`. 
https://github.com/cyclejs/cyclejs/blob/2f4ebc9e7f466ca7af7cc1f642001b8887dccb36/dom/src/EventDelegator.ts#L168-L176
However that does not seems to work, because the listeners are added to `this.nonBubblingListeners` when the stream starts, which is too late.
https://github.com/cyclejs/cyclejs/blob/2f4ebc9e7f466ca7af7cc1f642001b8887dccb36/dom/src/EventDelegator.ts#L181-L186
I am trying to fix the problem by adding the listener earlier, it runs fine to me but I am not familiar with the internals, is this …
=> Fix(dom): fix nonBubbling events only emit to one stream

dom/src/MainDOMSource.ts, dom/test/browser/isolation.ts
With `any` it prevents normal typing, with isolate.
=> fix: add VNode typing to IsolateSink

http/src/api.ts, run/src/index.ts, run/src/run.ts, run/src/types.ts, run/test/api.ts
As discussed in the big neocycle PR, this adds the `applyApis` function to manually unwrap apis at any point in your application. The nice thing is, that this is simply the code from `makeMasterMain` factored out together with some new types and tests.
=> [Cycle.js Neo] Allow to manually unwrap APIs

history/src/createHistory$.ts, history/src/types.ts
Similarly to what #890 did for `history.push()`. The `history` library [supports](https://github.com/ReactTraining/history/blob/master/docs/Navigation.md) accepting a location-like object for both methods.
BREAKING CHANGE: :firecracker: The search/hash has to be provided as separate fields and can no longer be included in the pathname.
=> feat: complete support for history.replace API

time/src/assert-equal.ts, time/src/diagram.ts, time/test/time.ts
There was some issues related to time diagrams:
1. during the parsing of grouped values, the scheduled time index kept on incrementing for each character
2. during the creation of streams from diagram *after* the scheduler started, the scheduled timestamp were still starting at time `0`
3. during the printing of diff errors, merged values taking more than 1 character were colliding on the
diagram because of their length
It all resulted in strange diagrams being printed in test reports
BREAKING CHANGE:
The scheduling of events is now more correct, but people depending on the current behavior will be
impacted
ISSUES CLOSED: #962, #963
(be indulgent for my english, it is not my first language)
=> Fix cycle time diagrams

docs/content/api/state.md, state/src/Collection.ts, state/src/types.ts, state/test/makeCollection.ts
Currently, `makeCollection` is meant for a list of child items where each child is from the **same** component. Thus homogenous collections. This PR allows `makeCollection` to have heterogenous child items, i.e., **different** components for the children.
I'm adapting Manyverse to run in Electron, and I'm having to build an alternative to [cycle-native-navigation](https://github.com/staltz/cycle-native-navigation), so I'm working with navigation logic. The basic architecture of my navigation solution is that there is a map of strings to components, such as
```js
const screenMap = {
"MainScreen": main,
"ProfileScreen": profile,
"SettingsScreen": settings,
}
```
And then there is the "stack" of screens, which is just an array that gets pushed when a new screen is opened, and gets popped …
=> cycle/state: Heterogenous Collections

dom/package.json, dom/src/IsolateModule.ts, dom/src/MainDOMSource.ts, dom/src/VNodeWrapper.ts, dom/src/hyperscript-helpers.ts, dom/src/index.ts, dom/src/isolate.ts, dom/src/makeDOMDriver.ts, dom/src/mockDOMSource.ts, dom/src/modules.ts, dom/src/thunk.ts, pnpm-lock.yaml
Addresses #944
After this pull request is merged, Snabbdom v0.x will no longer be supported.
So a major version bump is required.
=> [dom] Update Snabbdom to v3

time/README.md, time/package.json, time/src/index.ts, time/src/most.ts, time/src/rxjs.ts, time/test/jasmine-support.ts, time/test/most.ts, time/test/rxjs.ts, time/test/time-driver.ts, time/test/time.ts, time/test/xstream.ts, time/tsconfig.json, time/tsconfig.lint.json
Normalize the way of importing `rxjs` and `most` variants from `@cycle/time` as in `@cycle/dom` and `@cycle/http`.
**Breaking change**
If you are using RxJS change
`import {timeDriver} from '@cycle/time/rxjs'` to
`import {timeDriver} from '@cycle/time/lib/es6/rxjs'`.
If you are using Most.js change
`import {timeDriver} from '@cycle/time/most'` to
`import {timeDriver} from '@cycle/time/lib/es6/most'`.
Closes: #977
=> [time] Fix ModuleNotFoundError for RxJS and Most.js

dom/package.json, dom/src/makeDOMDriver.ts, pnpm-lock.yaml
Supported `options` arguments of Snabbdom's `init` function.
---
- This is a speculative pull request addressing https://github.com/snabbdom/snabbdom/pull/975#issuecomment-997180772, so feel free to close it if you don't need this.
- Do you have any ideas for what kind of test cases should be added?
=> Support Snabbdom options
